pipeline {
    agent any

    environment {
        AWS_REGION = "us-east-1"
        TF_IN_AUTOMATION = "true"
        TF_VAR_key_name = "devops-key"   // 👈 your AWS EC2 keypair NAME
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'release',
                    url: 'https://github.com/Aj066/challenge.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('ansible-challenge/terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('ansible-challenge/terraform') {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('ansible-challenge/terraform') {
                    sh '''
                    terraform apply -auto-approve
                    '''
                }
            }
        }

        stage('Generate Inventory') {
            steps {
                dir('ansible-challenge/terraform') {
                    sh 'terraform output -raw inventory > ../ansible/inventory.ini'
                }
            }
        }

        stage('Run Ansible') {
            steps {
                sshagent(['ec2-ssh-key']) {
                    dir('ansible-challenge/ansible') {
                        sh '''
                        ansible-playbook \
                        -i inventory.ini \
                        site.yml
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
