pipeline {
    agent any

    environment {
        AWS_REGION = "us-east-1"
        TF_IN_AUTOMATION = "true"
        TF_VAR_key_name = "ec2-user"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'release',
                    url: 'https://github.com/Aj066/challenge.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('ansible-challenge/terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('ansible-challenge/terraform') {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'aws-creds',
                    usernameVariable: 'AWS_ACCESS_KEY_ID',
                    passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                )]) {
                    dir('ansible-challenge/terraform') {
                        sh '''
                        export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
                        export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
                        terraform apply -auto-approve
                        '''
                    }
                }
            }
        }

        stage('Generate Inventory') {
            steps {
                dir('ansible-challenge/terraform') {
                    sh 'terraform output -raw inventory > ../ansible/inventory.ini'
                }
            }
        }

        stage('Run Ansible') {
            steps {
                sshagent(['ec2-ssh-key']) {
                    dir('ansible-challenge/ansible') {
                        sh 'ansible-playbook -i inventory.ini site.yml'
                    }
                }
            }
        }
    }

    post {
        success { echo 'Deployment successful!' }
        failure { echo 'Pipeline failed!' }
    }
}
